language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc-4.8
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

    - os: linux
      addons:
        apt:
          packages:
            - gcc-5.4
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5.4 && CXX=g++-5.4"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - git clone https://github.com/satya-das/cib.git
  - git clone https://github.com/satya-das/cppparser.git
  - git clone https://github.com/satya-das/common.git
  - mkdir -p build_results/Clang
  - cd build_results/Clang
  - cmake ../../cib
  - make

after_success:
  - make test

