language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-5
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - git clone https://github.com/satya-das/cib.git
  - git clone https://github.com/satya-das/cppparser.git
  - git clone https://github.com/satya-das/common.git
  - mkdir -p build_results/Clang
  - cd build_results/Clang
  - cmake ../../cib
  - make

after_success:
  - make test

