language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-5
            - cmake-data
            - cmake
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - git clone https://github.com/satya-das/cib.git
  - git clone https://github.com/satya-das/cppparser.git
  - git clone https://github.com/satya-das/common.git
  - mkdir -p build_results/GNU
  - cd build_results/GNU
  - cmake -DCMAKE_C_COMPILER=`which gcc-5` -DCMAKE_CXX_COMPILER=`which g++-5` ../../cib/
  - make
  - make test

#after_success:
#  - make test
# It's not working.

